version: "3.7"

services:
  db:
    container_name: questions-db
    image: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 5433:5432
    restart: on-failure
    environment:
      POSTGRES_DB: questions
      POSTGRES_HOST: localhost
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_PORT: 5433
    healthcheck:
      test: "exit 0"

volumes:
  db-data:
