# Generated by Django 3.1.6 on 2021-02-09 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_answer_question_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='creation_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
