# Generated by Django 3.1.6 on 2021-02-11 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='order',
        ),
        migrations.AddField(
            model_name='test',
            name='state',
            field=models.CharField(choices=[('A', 'Creating'), ('Z', 'Created')], default='A', max_length=100),
        ),
    ]
