# Generated by Django 3.1.6 on 2021-02-11 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210211_0852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='passes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
